//products action types
export const GET_ALL_PRODUCTS_START = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_SUCCESS = "GET_ALL_PRODUCTS_SUCCESS";
export const GET_ALL_PRODUCTS_FAIL = "GET_ALL_PRODUCTS_FAIL";

//cart products action types
export const GET_CART_PRODUCTS = "GET_CART_PRODUCTS";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const ADD_TO_CART = "ADD_TO_CART";

//authentication action types
export const SIGNIN_START = "SIGNIN_START";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_FAIL = "SIGNIN_FAIL";
export const LOGOUT = "LOGOUT";

//Create order from cart
export const ADD_TO_ORDER_START = "ADD_TO_ORDER_START";
export const ADD_TO_ORDER_SUCCESS = "ADD_TO_ORDER_SUCCESS";
export const ADD_TO_ORDER_ERROR = "ADD_TO_ORDER_ERROR";
export const CLEAR_CART = "CLEAR_CART";

//Get orders of specific user
export const GET_ORDERS_START = "GET_ORDERS_START";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAIL = "GET_ORDERS_SUCCESS";
export const DELETE_ORDER_START = "DELETE_ORDER_START";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";

//Create favourites action types
export const GET_FAVOURITE_PRODUCTS_START = "GET_FAVOURITE_PRODUCTS_START";
export const GET_FAVOURITE_PRODUCTS_SUCCESS = "GET_FAVOURITE_PRODUCTS_SUCCESS";
export const GET_FAVOURITE_PRODUCTS_FAIL = "GET_FAVOURITE_PRODUCTS_FAIL";
export const FAVOURITE_PRODUCTS_FAIL = "FAVOURITE_PRODUCTS_FAIL";
export const ADD_TO_FAVOURITE_PRODUCTS_SUCCESS =
  "ADD_TO_FAVOURITE_PRODUCTS_SUCCESS";
export const DELETE_FAVOURITE_PRODUCT_SUCCESS =
  "DELETE_FAVOURITE_PRODUCT_SUCCESS";
